/**
 * Pine Script V6 Function Behavior Metadata
 *
 * This module provides access to empirically discovered function behavior:
 * - Polymorphism: which functions return types based on input
 * - Argument ordering: which functions support named/reordered arguments
 *
 * Data is generated by: pnpm run discover:behavior
 */

import * as fs from "node:fs";
import * as path from "node:path";

// Behavior metadata types
export interface PolymorphicBehavior {
	returnTypeParam: string;
	strategy: "same-as-input" | "dependent-on-input";
	observedMappings: Record<string, string>;
	allowedTypes?: string[];
}

export interface FunctionBehavior {
	polymorphic: PolymorphicBehavior | false;
	argumentOrdering: "flexible" | "positional-only";
	reason?: string;
	observedReturnTypes?: string[];
}

export interface BehaviorMetadata {
	version: string;
	generatedAt: string;
	functions: Record<string, FunctionBehavior>;
}

// Lazy-loaded behavior data
let _behaviorData: BehaviorMetadata | null = null;

/**
 * Load behavior metadata from JSON file
 */
function loadBehaviorData(): BehaviorMetadata {
	if (_behaviorData) {
		return _behaviorData;
	}

	try {
		const jsonPath = path.join(__dirname, "function-behavior.json");
		const jsonContent = fs.readFileSync(jsonPath, "utf-8");
		_behaviorData = JSON.parse(jsonContent) as BehaviorMetadata;
		return _behaviorData;
	} catch {
		// Return empty metadata if file doesn't exist
		_behaviorData = {
			version: "6",
			generatedAt: new Date().toISOString(),
			functions: {},
		};
		return _behaviorData;
	}
}

/**
 * Get behavior metadata for a specific function
 */
export function getFunctionBehavior(functionName: string): FunctionBehavior | undefined {
	const data = loadBehaviorData();
	return data.functions[functionName];
}

/**
 * Check if a function is polymorphic (return type depends on input)
 */
export function isPolymorphicFunction(functionName: string): boolean {
	const behavior = getFunctionBehavior(functionName);
	return behavior?.polymorphic !== false && behavior?.polymorphic !== undefined;
}

/**
 * Get the parameter name that determines return type for polymorphic functions
 */
export function getReturnTypeParam(functionName: string): string | undefined {
	const behavior = getFunctionBehavior(functionName);
	if (behavior?.polymorphic) {
		return behavior.polymorphic.returnTypeParam;
	}
	return undefined;
}

/**
 * Check if a function supports flexible argument ordering (named args in any order)
 */
export function supportsFlexibleOrdering(functionName: string): boolean {
	const behavior = getFunctionBehavior(functionName);
	// Default to true (most functions support it)
	return behavior?.argumentOrdering !== "positional-only";
}

/**
 * Get all function behaviors
 */
export function getAllBehaviors(): Record<string, FunctionBehavior> {
	const data = loadBehaviorData();
	return data.functions;
}

/**
 * Re-export the behavior data for direct access
 */
export const FUNCTION_BEHAVIORS = {
	get: getFunctionBehavior,
	isPolymorphic: isPolymorphicFunction,
	getReturnTypeParam,
	supportsFlexibleOrdering,
	getAll: getAllBehaviors,
};
